### PR TITLE
rewrite most of the website

### PR DESCRIPTION
**Pull request by OncePunchedMan**
Will slowly update the website

### CODE REVIEW

**Comment by OncePunchedMan** [comment]
you wanna remove all manga related stuff and only keep anime or both?

**Comment by jmir1** [comment]
In theory, it would be great to reword every single article so that it makes sense when talking about aniyomi. Cause tachi's website is pretty useful for a lot of users, but obviously it's rather confusing rn.

Would be a lot of work tho so the easier option is removing everything and just keeping the local anime guide (currently the whole purpose of this website)

**Comment by OncePunchedMan** [comment]
ok, so i renamed most of the stuff to include anime. will check a preview build tonight or so to test it

**Comment by OncePunchedMan** [comment]
don't merge unless you can deploy a preview

**Comment by OncePunchedMan** [comment]
idk if you can test it, but here is the preview: https://deploy-preview-2--aniyomi-preview-opb.netlify.app/

pls give me a svg of the logo if you got one, so i can replace the one i chose

**Comment by jmir1** [comment]
yeah looks good
logo looks kinda shit but don't stress about it

**Comment by OncePunchedMan** [comment]
> yeah looks good logo looks kinda shit but don't stress about it

ye gib new one

**Comment by OncePunchedMan** [comment]
check the preview. kinda done with all. might have mied some things but overall should be done

**Comment by jmir1** [comment]
THANK YOU

**Pull request merged**
